postgresql-ha:
  commonAnnotations:
    ves.io/virtual-sites: "ha-services-ce/aws-ha-vs"

  clusterDomain: aws-ha.tme-lab-works-oeaclgke.tenant.local  

  persistence:
    enabled: true
    size: 1Gi

  witness:
    create: false
    pdb:
      create: false

  postgresql:
    image:
      registry: ghcr.io
      repository: f5devcentral/xchaawsdemoguide/postgresql-repmgr
      tag: 17.6.0-debian-12-r2
    networkPolicy:
      enabled: false
    pdb:
      create: false
    resources:
      requests:
        memory: 256Mi
        cpu: 5m
      limits:
        memory: 512Mi
        cpu: 1500m

    containerSecurityContext:
      runAsNonRoot: true

    replicaCount: 3
    username: haservices
    password: haservicespass
    database: haservicesdb
    repmgrUsername: haservices
    repmgrPassword: haservicespass
    repmgrDatabase: repmgrhaservicesdb

  pgpool:
    networkPolicy:
      enabled: false
    pdb:
      create: false
    image:
      registry: ghcr.io
      repository: f5devcentral/xchaawsdemoguide/pgpool
      tag: 4.6.3-debian-12-r0
    
    adminUsername: haservices
    adminPassword: haservicespass



