apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  {{- with .Values.nginx.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
